server:
 # context-path: /api/v1
  port: 8087

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.26.137.230:3306/ua?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  # 404 交给异常处理器处理
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
#  thymeleaf:
#    mode: LEGACYHTML5
